// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/larissamartinsss/simple-banking-api/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockCreateAccountProcessorInterface is an autogenerated mock type for the CreateAccountProcessorInterface type
type MockCreateAccountProcessorInterface struct {
	mock.Mock
}

type MockCreateAccountProcessorInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreateAccountProcessorInterface) EXPECT() *MockCreateAccountProcessorInterface_Expecter {
	return &MockCreateAccountProcessorInterface_Expecter{mock: &_m.Mock}
}

// Process provides a mock function with given fields: ctx, req
func (_m *MockCreateAccountProcessorInterface) Process(ctx context.Context, req domain.CreateAccountRequest) (*domain.CreateAccountResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Process")
	}

	var r0 *domain.CreateAccountResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.CreateAccountRequest) (*domain.CreateAccountResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.CreateAccountRequest) *domain.CreateAccountResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.CreateAccountResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.CreateAccountRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCreateAccountProcessorInterface_Process_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Process'
type MockCreateAccountProcessorInterface_Process_Call struct {
	*mock.Call
}

// Process is a helper method to define mock.On call
//   - ctx context.Context
//   - req domain.CreateAccountRequest
func (_e *MockCreateAccountProcessorInterface_Expecter) Process(ctx interface{}, req interface{}) *MockCreateAccountProcessorInterface_Process_Call {
	return &MockCreateAccountProcessorInterface_Process_Call{Call: _e.mock.On("Process", ctx, req)}
}

func (_c *MockCreateAccountProcessorInterface_Process_Call) Run(run func(ctx context.Context, req domain.CreateAccountRequest)) *MockCreateAccountProcessorInterface_Process_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.CreateAccountRequest))
	})
	return _c
}

func (_c *MockCreateAccountProcessorInterface_Process_Call) Return(_a0 *domain.CreateAccountResponse, _a1 error) *MockCreateAccountProcessorInterface_Process_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCreateAccountProcessorInterface_Process_Call) RunAndReturn(run func(context.Context, domain.CreateAccountRequest) (*domain.CreateAccountResponse, error)) *MockCreateAccountProcessorInterface_Process_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCreateAccountProcessorInterface creates a new instance of MockCreateAccountProcessorInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreateAccountProcessorInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreateAccountProcessorInterface {
	mock := &MockCreateAccountProcessorInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
