// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/larissamartinsss/simple-banking-api/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockGetTransactionsProcessorInterface is an autogenerated mock type for the GetTransactionsProcessorInterface type
type MockGetTransactionsProcessorInterface struct {
	mock.Mock
}

type MockGetTransactionsProcessorInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetTransactionsProcessorInterface) EXPECT() *MockGetTransactionsProcessorInterface_Expecter {
	return &MockGetTransactionsProcessorInterface_Expecter{mock: &_m.Mock}
}

// Process provides a mock function with given fields: ctx, req
func (_m *MockGetTransactionsProcessorInterface) Process(ctx context.Context, req domain.GetTransactionsRequest) (*domain.GetTransactionsResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Process")
	}

	var r0 *domain.GetTransactionsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.GetTransactionsRequest) (*domain.GetTransactionsResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.GetTransactionsRequest) *domain.GetTransactionsResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.GetTransactionsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.GetTransactionsRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGetTransactionsProcessorInterface_Process_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Process'
type MockGetTransactionsProcessorInterface_Process_Call struct {
	*mock.Call
}

// Process is a helper method to define mock.On call
//   - ctx context.Context
//   - req domain.GetTransactionsRequest
func (_e *MockGetTransactionsProcessorInterface_Expecter) Process(ctx interface{}, req interface{}) *MockGetTransactionsProcessorInterface_Process_Call {
	return &MockGetTransactionsProcessorInterface_Process_Call{Call: _e.mock.On("Process", ctx, req)}
}

func (_c *MockGetTransactionsProcessorInterface_Process_Call) Run(run func(ctx context.Context, req domain.GetTransactionsRequest)) *MockGetTransactionsProcessorInterface_Process_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.GetTransactionsRequest))
	})
	return _c
}

func (_c *MockGetTransactionsProcessorInterface_Process_Call) Return(_a0 *domain.GetTransactionsResponse, _a1 error) *MockGetTransactionsProcessorInterface_Process_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGetTransactionsProcessorInterface_Process_Call) RunAndReturn(run func(context.Context, domain.GetTransactionsRequest) (*domain.GetTransactionsResponse, error)) *MockGetTransactionsProcessorInterface_Process_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetTransactionsProcessorInterface creates a new instance of MockGetTransactionsProcessorInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetTransactionsProcessorInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetTransactionsProcessorInterface {
	mock := &MockGetTransactionsProcessorInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
