// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/larissamartinsss/simple-banking-api/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockCreateTransactionProcessorInterface is an autogenerated mock type for the CreateTransactionProcessorInterface type
type MockCreateTransactionProcessorInterface struct {
	mock.Mock
}

type MockCreateTransactionProcessorInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreateTransactionProcessorInterface) EXPECT() *MockCreateTransactionProcessorInterface_Expecter {
	return &MockCreateTransactionProcessorInterface_Expecter{mock: &_m.Mock}
}

// Process provides a mock function with given fields: ctx, req
func (_m *MockCreateTransactionProcessorInterface) Process(ctx context.Context, req domain.CreateTransactionRequest) (*domain.CreateTransactionResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Process")
	}

	var r0 *domain.CreateTransactionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.CreateTransactionRequest) (*domain.CreateTransactionResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.CreateTransactionRequest) *domain.CreateTransactionResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.CreateTransactionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.CreateTransactionRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCreateTransactionProcessorInterface_Process_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Process'
type MockCreateTransactionProcessorInterface_Process_Call struct {
	*mock.Call
}

// Process is a helper method to define mock.On call
//   - ctx context.Context
//   - req domain.CreateTransactionRequest
func (_e *MockCreateTransactionProcessorInterface_Expecter) Process(ctx interface{}, req interface{}) *MockCreateTransactionProcessorInterface_Process_Call {
	return &MockCreateTransactionProcessorInterface_Process_Call{Call: _e.mock.On("Process", ctx, req)}
}

func (_c *MockCreateTransactionProcessorInterface_Process_Call) Run(run func(ctx context.Context, req domain.CreateTransactionRequest)) *MockCreateTransactionProcessorInterface_Process_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.CreateTransactionRequest))
	})
	return _c
}

func (_c *MockCreateTransactionProcessorInterface_Process_Call) Return(_a0 *domain.CreateTransactionResponse, _a1 error) *MockCreateTransactionProcessorInterface_Process_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCreateTransactionProcessorInterface_Process_Call) RunAndReturn(run func(context.Context, domain.CreateTransactionRequest) (*domain.CreateTransactionResponse, error)) *MockCreateTransactionProcessorInterface_Process_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCreateTransactionProcessorInterface creates a new instance of MockCreateTransactionProcessorInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreateTransactionProcessorInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreateTransactionProcessorInterface {
	mock := &MockCreateTransactionProcessorInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
