// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/larissamartinsss/simple-banking-api/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockTransactionRepository is an autogenerated mock type for the TransactionRepository type
type MockTransactionRepository struct {
	mock.Mock
}

type MockTransactionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionRepository) EXPECT() *MockTransactionRepository_Expecter {
	return &MockTransactionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, transaction
func (_m *MockTransactionRepository) Create(ctx context.Context, transaction *domain.Transaction) (*domain.Transaction, error) {
	ret := _m.Called(ctx, transaction)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Transaction) (*domain.Transaction, error)); ok {
		return rf(ctx, transaction)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Transaction) *domain.Transaction); ok {
		r0 = rf(ctx, transaction)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Transaction) error); ok {
		r1 = rf(ctx, transaction)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTransactionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - transaction *domain.Transaction
func (_e *MockTransactionRepository_Expecter) Create(ctx interface{}, transaction interface{}) *MockTransactionRepository_Create_Call {
	return &MockTransactionRepository_Create_Call{Call: _e.mock.On("Create", ctx, transaction)}
}

func (_c *MockTransactionRepository_Create_Call) Run(run func(ctx context.Context, transaction *domain.Transaction)) *MockTransactionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Transaction))
	})
	return _c
}

func (_c *MockTransactionRepository_Create_Call) Return(_a0 *domain.Transaction, _a1 error) *MockTransactionRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Transaction) (*domain.Transaction, error)) *MockTransactionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByAccountID provides a mock function with given fields: ctx, accountID
func (_m *MockTransactionRepository) FindByAccountID(ctx context.Context, accountID int64) ([]*domain.Transaction, error) {
	ret := _m.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for FindByAccountID")
	}

	var r0 []*domain.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]*domain.Transaction, error)); ok {
		return rf(ctx, accountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []*domain.Transaction); ok {
		r0 = rf(ctx, accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionRepository_FindByAccountID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByAccountID'
type MockTransactionRepository_FindByAccountID_Call struct {
	*mock.Call
}

// FindByAccountID is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID int64
func (_e *MockTransactionRepository_Expecter) FindByAccountID(ctx interface{}, accountID interface{}) *MockTransactionRepository_FindByAccountID_Call {
	return &MockTransactionRepository_FindByAccountID_Call{Call: _e.mock.On("FindByAccountID", ctx, accountID)}
}

func (_c *MockTransactionRepository_FindByAccountID_Call) Run(run func(ctx context.Context, accountID int64)) *MockTransactionRepository_FindByAccountID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockTransactionRepository_FindByAccountID_Call) Return(_a0 []*domain.Transaction, _a1 error) *MockTransactionRepository_FindByAccountID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionRepository_FindByAccountID_Call) RunAndReturn(run func(context.Context, int64) ([]*domain.Transaction, error)) *MockTransactionRepository_FindByAccountID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByAccountIDPaginated provides a mock function with given fields: ctx, accountID, limit, offset
func (_m *MockTransactionRepository) FindByAccountIDPaginated(ctx context.Context, accountID int64, limit int64, offset int64) ([]*domain.Transaction, int64, error) {
	ret := _m.Called(ctx, accountID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for FindByAccountIDPaginated")
	}

	var r0 []*domain.Transaction
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, int64) ([]*domain.Transaction, int64, error)); ok {
		return rf(ctx, accountID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, int64) []*domain.Transaction); ok {
		r0 = rf(ctx, accountID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64, int64) int64); ok {
		r1 = rf(ctx, accountID, limit, offset)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int64, int64, int64) error); ok {
		r2 = rf(ctx, accountID, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockTransactionRepository_FindByAccountIDPaginated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByAccountIDPaginated'
type MockTransactionRepository_FindByAccountIDPaginated_Call struct {
	*mock.Call
}

// FindByAccountIDPaginated is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID int64
//   - limit int64
//   - offset int64
func (_e *MockTransactionRepository_Expecter) FindByAccountIDPaginated(ctx interface{}, accountID interface{}, limit interface{}, offset interface{}) *MockTransactionRepository_FindByAccountIDPaginated_Call {
	return &MockTransactionRepository_FindByAccountIDPaginated_Call{Call: _e.mock.On("FindByAccountIDPaginated", ctx, accountID, limit, offset)}
}

func (_c *MockTransactionRepository_FindByAccountIDPaginated_Call) Run(run func(ctx context.Context, accountID int64, limit int64, offset int64)) *MockTransactionRepository_FindByAccountIDPaginated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64), args[3].(int64))
	})
	return _c
}

func (_c *MockTransactionRepository_FindByAccountIDPaginated_Call) Return(_a0 []*domain.Transaction, _a1 int64, _a2 error) *MockTransactionRepository_FindByAccountIDPaginated_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockTransactionRepository_FindByAccountIDPaginated_Call) RunAndReturn(run func(context.Context, int64, int64, int64) ([]*domain.Transaction, int64, error)) *MockTransactionRepository_FindByAccountIDPaginated_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockTransactionRepository) FindByID(ctx context.Context, id int64) (*domain.Transaction, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*domain.Transaction, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *domain.Transaction); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockTransactionRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockTransactionRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockTransactionRepository_FindByID_Call {
	return &MockTransactionRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockTransactionRepository_FindByID_Call) Run(run func(ctx context.Context, id int64)) *MockTransactionRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockTransactionRepository_FindByID_Call) Return(_a0 *domain.Transaction, _a1 error) *MockTransactionRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionRepository_FindByID_Call) RunAndReturn(run func(context.Context, int64) (*domain.Transaction, error)) *MockTransactionRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: ctx
func (_m *MockTransactionRepository) GetAll(ctx context.Context) ([]*domain.Transaction, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*domain.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*domain.Transaction, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*domain.Transaction); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockTransactionRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTransactionRepository_Expecter) GetAll(ctx interface{}) *MockTransactionRepository_GetAll_Call {
	return &MockTransactionRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *MockTransactionRepository_GetAll_Call) Run(run func(ctx context.Context)) *MockTransactionRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockTransactionRepository_GetAll_Call) Return(_a0 []*domain.Transaction, _a1 error) *MockTransactionRepository_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionRepository_GetAll_Call) RunAndReturn(run func(context.Context) ([]*domain.Transaction, error)) *MockTransactionRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransactionRepository creates a new instance of MockTransactionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionRepository {
	mock := &MockTransactionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
