// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/larissamartinsss/simple-banking-api/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockOperationTypeRepository is an autogenerated mock type for the OperationTypeRepository type
type MockOperationTypeRepository struct {
	mock.Mock
}

type MockOperationTypeRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOperationTypeRepository) EXPECT() *MockOperationTypeRepository_Expecter {
	return &MockOperationTypeRepository_Expecter{mock: &_m.Mock}
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockOperationTypeRepository) FindByID(ctx context.Context, id int64) (*domain.OperationType, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.OperationType
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*domain.OperationType, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *domain.OperationType); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.OperationType)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOperationTypeRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockOperationTypeRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockOperationTypeRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockOperationTypeRepository_FindByID_Call {
	return &MockOperationTypeRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockOperationTypeRepository_FindByID_Call) Run(run func(ctx context.Context, id int64)) *MockOperationTypeRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockOperationTypeRepository_FindByID_Call) Return(_a0 *domain.OperationType, _a1 error) *MockOperationTypeRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOperationTypeRepository_FindByID_Call) RunAndReturn(run func(context.Context, int64) (*domain.OperationType, error)) *MockOperationTypeRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: ctx
func (_m *MockOperationTypeRepository) GetAll(ctx context.Context) ([]*domain.OperationType, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*domain.OperationType
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*domain.OperationType, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*domain.OperationType); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.OperationType)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOperationTypeRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockOperationTypeRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockOperationTypeRepository_Expecter) GetAll(ctx interface{}) *MockOperationTypeRepository_GetAll_Call {
	return &MockOperationTypeRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *MockOperationTypeRepository_GetAll_Call) Run(run func(ctx context.Context)) *MockOperationTypeRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockOperationTypeRepository_GetAll_Call) Return(_a0 []*domain.OperationType, _a1 error) *MockOperationTypeRepository_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOperationTypeRepository_GetAll_Call) RunAndReturn(run func(context.Context) ([]*domain.OperationType, error)) *MockOperationTypeRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// Seed provides a mock function with given fields: ctx
func (_m *MockOperationTypeRepository) Seed(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Seed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOperationTypeRepository_Seed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Seed'
type MockOperationTypeRepository_Seed_Call struct {
	*mock.Call
}

// Seed is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockOperationTypeRepository_Expecter) Seed(ctx interface{}) *MockOperationTypeRepository_Seed_Call {
	return &MockOperationTypeRepository_Seed_Call{Call: _e.mock.On("Seed", ctx)}
}

func (_c *MockOperationTypeRepository_Seed_Call) Run(run func(ctx context.Context)) *MockOperationTypeRepository_Seed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockOperationTypeRepository_Seed_Call) Return(_a0 error) *MockOperationTypeRepository_Seed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOperationTypeRepository_Seed_Call) RunAndReturn(run func(context.Context) error) *MockOperationTypeRepository_Seed_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOperationTypeRepository creates a new instance of MockOperationTypeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOperationTypeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOperationTypeRepository {
	mock := &MockOperationTypeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
